"""empty message

Revision ID: 0a874b7c95ad
Revises: b1a25588085e
Create Date: 2024-06-15 16:08:40.487661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a874b7c95ad'
down_revision = 'b1a25588085e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('ancho', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('alto', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('largo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'largo')
    op.drop_column('productos', 'alto')
    op.drop_column('productos', 'ancho')
    # ### end Alembic commands ###
