"""creacion_base_de_datos

Revision ID: 184a168804da
Revises: 
Create Date: 2024-06-14 15:25:23.290645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184a168804da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_nombre'), 'areas', ['nombre'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=True)
    op.create_index(op.f('ix_clientes_rut'), 'clientes', ['rut'], unique=True)
    op.create_table('colores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colores_nombre'), 'colores', ['nombre'], unique=True)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_nombre'), 'grupos', ['nombre'], unique=True)
    op.create_table('lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineas_nombre'), 'lineas', ['nombre'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('tamanos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('largo', sa.Integer(), nullable=False),
    sa.Column('ancho', sa.Integer(), nullable=False),
    sa.Column('alto', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_incidentes_nombre'), 'tipos_incidentes', ['nombre'], unique=True)
    op.create_table('factores_tiempos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('alto', sa.Integer(), nullable=False),
    sa.Column('ancho', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['lineas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_codigo'), 'productos', ['codigo'], unique=True)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=25), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=25), nullable=True),
    sa.Column('apellido', sa.String(length=25), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=25), nullable=True),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_apellido'), 'usuarios', ['apellido'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=False)
    op.create_index(op.f('ix_usuarios_rut'), 'usuarios', ['rut'], unique=True)
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_orden', sa.String(length=50), nullable=False, comment='Número de orden por parte de la empresa'),
    sa.Column('fecha', sa.DateTime(), nullable=False, comment='Fecha de creacion la orden'),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=False, comment='Fecha de entrega de la orden'),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tamano_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['colores.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['tamano_id'], ['tamanos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_nro_orden'), 'ordenes', ['nro_orden'], unique=False)
    op.create_table('roles_usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('tiempos_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiempos', sa.Integer(), nullable=False, comment='Tiempo en segundos que se demora el Area en realizar una actividad'),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora_ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=True, comment='Fecha de inicio de la actividad'),
    sa.Column('fin', sa.DateTime(), nullable=True, comment='Fecha de fin de la actividad'),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False, comment='Usuario que reporta el incidente'),
    sa.Column('tipo_incidente_id', sa.Integer(), nullable=False, comment='Tipo de incidente'),
    sa.Column('observaciones', sa.String(length=250), nullable=False, comment='Comentarios del incidente'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualizacion del registro'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminacion del registro'),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.ForeignKeyConstraint(['tipo_incidente_id'], ['tipos_incidentes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidentes')
    op.drop_table('bitacora_ordenes')
    op.drop_table('tiempos_area')
    op.drop_table('roles_usuarios')
    op.drop_index(op.f('ix_ordenes_nro_orden'), table_name='ordenes')
    op.drop_table('ordenes')
    op.drop_index(op.f('ix_usuarios_rut'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_apellido'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo'), table_name='productos')
    op.drop_table('productos')
    op.drop_table('factores_tiempos')
    op.drop_index(op.f('ix_tipos_incidentes_nombre'), table_name='tipos_incidentes')
    op.drop_table('tipos_incidentes')
    op.drop_table('tamanos')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_lineas_nombre'), table_name='lineas')
    op.drop_table('lineas')
    op.drop_index(op.f('ix_grupos_nombre'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_colores_nombre'), table_name='colores')
    op.drop_table('colores')
    op.drop_index(op.f('ix_clientes_rut'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_areas_nombre'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
