"""empty message

Revision ID: 4069e6198f32
Revises: 53f010415f02
Create Date: 2024-06-20 15:53:01.124221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4069e6198f32'
down_revision = '53f010415f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidentes', sa.Column('area_id', sa.Integer(), nullable=True, comment='Area donde se reporta el incidente'))
    op.create_foreign_key(None, 'incidentes', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidentes', type_='foreignkey')
    op.drop_column('incidentes', 'area_id')
    # ### end Alembic commands ###
