"""empty message

Revision ID: 4be5eb508766
Revises: 7fd910e7d31c
Create Date: 2024-06-15 12:29:31.124517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be5eb508766'
down_revision = '7fd910e7d31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colores', sa.Column('descripcion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colores', 'descripcion')
    # ### end Alembic commands ###
