"""empty message

Revision ID: 4f55d2902317
Revises: d85e41e9a86e
Create Date: 2024-06-24 17:30:09.490146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f55d2902317'
down_revision = 'd85e41e9a86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tamanos', sa.Column('producto_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tamanos', 'producto_id')
    # ### end Alembic commands ###
