"""empty message

Revision ID: 7fd910e7d31c
Revises: af440ce3d155
Create Date: 2024-06-15 00:59:32.983998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd910e7d31c'
down_revision = 'af440ce3d155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'grupo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'grupo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
