"""empty message

Revision ID: 9e45f14b1687
Revises: 4069e6198f32
Create Date: 2024-06-22 21:29:09.541994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e45f14b1687'
down_revision = '4069e6198f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidentes', 'observaciones',
               existing_type=sa.VARCHAR(length=250),
               nullable=True,
               existing_comment='Comentarios del incidente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidentes', 'observaciones',
               existing_type=sa.VARCHAR(length=250),
               nullable=False,
               existing_comment='Comentarios del incidente')
    # ### end Alembic commands ###
