"""add_descripcion_grupo

Revision ID: a65537abf02b
Revises: 160199235ee7
Create Date: 2024-06-15 16:41:17.274669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65537abf02b'
down_revision = '160199235ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos', sa.Column('descripcion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grupos', 'descripcion')
    # ### end Alembic commands ###
