"""empty message

Revision ID: c0d3ed2f3853
Revises: e9edf2a7d879
Create Date: 2024-06-24 19:37:34.546555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d3ed2f3853'
down_revision = 'e9edf2a7d879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'ancho')
    op.drop_column('productos', 'alto')
    op.drop_column('productos', 'largo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('largo', sa.INTEGER(), autoincrement=False, nullable=True, comment='Largo en centimetros'))
    op.add_column('productos', sa.Column('alto', sa.INTEGER(), autoincrement=False, nullable=True, comment='Alto en centimetros'))
    op.add_column('productos', sa.Column('ancho', sa.INTEGER(), autoincrement=False, nullable=True, comment='Ancho en centimetros'))
    # ### end Alembic commands ###
