"""empty message

Revision ID: e6b9d3775965
Revises: a65537abf02b
Create Date: 2024-06-15 20:07:39.398500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b9d3775965'
down_revision = 'a65537abf02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes', sa.Column('ancho', sa.Integer(), nullable=True))
    op.add_column('ordenes', sa.Column('alto', sa.Integer(), nullable=True))
    op.add_column('ordenes', sa.Column('largo', sa.Integer(), nullable=True))
    op.drop_constraint('ordenes_tamano_id_fkey', 'ordenes', type_='foreignkey')
    op.drop_column('ordenes', 'tamano_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes', sa.Column('tamano_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ordenes_tamano_id_fkey', 'ordenes', 'tamanos', ['tamano_id'], ['id'])
    op.drop_column('ordenes', 'largo')
    op.drop_column('ordenes', 'alto')
    op.drop_column('ordenes', 'ancho')
    # ### end Alembic commands ###
