"""empty message

Revision ID: e7b78b1f394e
Revises: c0d3ed2f3853
Create Date: 2024-08-28 15:29:55.985387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b78b1f394e'
down_revision = 'c0d3ed2f3853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bitacora_ordenes', sa.Column('estado', sa.String(), nullable=True, comment='Estado de la actividad'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bitacora_ordenes', 'estado')
    # ### end Alembic commands ###
