"""add_foreignkey_produto_tamanos

Revision ID: e9edf2a7d879
Revises: 4f55d2902317
Create Date: 2024-06-24 17:37:45.238862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9edf2a7d879'
down_revision = '4f55d2902317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tamanos', 'productos', ['producto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tamanos', type_='foreignkey')
    # ### end Alembic commands ###
